version: '3.9'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
